services:
  web:
    container_name: kentaro_portfolio
    build:
      context: .
      dockerfile: Dockerfile.prod
    # プロジェクト作成時はcommandをコメントアウト（コンテナが立ち上がらないため）
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./certs/isrgrootx1.pem:/etc/ssl/certs/isrgrootx1.pem
      - .:/app
    env_file:
      - .env
    ports:
      - ${RAILS_PORT}:3000 # 環境変数から参照
    tty: true
    # 標準入出力とエラー出力をコンテナに結びつける設定。
    stdin_open: true
    depends_on:
      - db
  # MySQLの設定
  db:
    container_name: kentaro_portfolio_db
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${STACKHERO_MYSQL_DATABASE} # 環境変数から参照
      MYSQL_USER: ${STACKHERO_MYSQL_USER} # 環境変数から参照
      MYSQL_PASSWORD: ${STACKHERO_MYSQL_ROOT_PASSWORD} # 環境変数から参照
      MYSQL_ROOT_PASSWORD: ${STACKHERO_MYSQL_ROOT_PASSWORD} # 環境変数から参照
      TZ: "Asia/Tokyo"
    ports:
      - "${STACKHERO_MYSQL_PORT}:3306" # 環境変数から参照
volumes:
  db-data:
