default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("MYSQL_DB") %>_development
  username: <%= ENV.fetch("MYSQL_USER") %>
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") %>
  host: db
  port: <%= ENV.fetch("MYSQL_PORT") { 3306 } %>

development:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DB") %>_development

test:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DB") %>_test


production:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DB", '') %>_production
  username: <%= ENV.fetch("MYSQL_USER", '') %>
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD", '') %>
  host: <%= ENV.fetch("MYSQL_HOST", '') %> # 本番環境の場合は環境変数から参照
  port: <%= ENV.fetch("MYSQL_PORT", '') %>
