default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("MYSQL_DB") %>_development
  username: <%= ENV.fetch("MYSQL_USER") %>
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") %>
  host: db
  port: <%= ENV.fetch("MYSQL_PORT") { 3306 } %>

development:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DB") %>_development

test:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DB") %>_test


production:
  <<: *default
  database: <%= ENV.fetch("STACKHERO_MYSQL_DATABASE", "portfolio_blog") %> # 明示的にデータベース名を指定
  username: <%= ENV.fetch("STACKHERO_MYSQL_USER", "root") %> # 環境変数から取得、デフォルトで root を設定
  password: <%= ENV.fetch("STACKHERO_MYSQL_ROOT_PASSWORD", '') %> # 環境変数からパスワードを取得
  host: <%= ENV.fetch("STACKHERO_MYSQL_HOST", '') %> # 環境変数からホストを取得
  port: <%= ENV.fetch("STACKHERO_MYSQL_PORT", '') %> # 環境変数からポートを取得
