default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV['PG_USER'] || 'your_local_username' %>
  password: <%= ENV['PG_PASSWORD'] || 'your_local_password' %>
  host: <%= ENV['PG_HOST'] || 'localhost' %>
  timeout: 5000

development:
  <<: *default
  database: development_database_name

test:
  <<: *default
  database: test_database_name

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

action_cable_production:
  <<: *default
  url: <%= ENV['CABLE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
