default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV['STACKHERO_MYSQL_USER'] || ENV['MYSQL_USER'] %>
  password: <%= ENV['STACKHERO_MYSQL_ROOT_PASSWORD'] || ENV['MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV['STACKHERO_MYSQL_HOST'] || 'localhost' %>
  port: <%= ENV['STACKHERO_MYSQL_PORT'] || ENV['MYSQL_PORT'] %>
  database: <%= ENV['STACKHERO_MYSQL_DATABASE'] || ENV['MYSQL_DB'] %>

development:
  <<: *default
  database: <%= ENV['MYSQL_DB'] %>

test:
  <<: *default
  database: <%= ENV['MYSQL_DB'] %>_test

production:
  <<: *default
  database: <%= ENV['STACKHERO_MYSQL_DATABASE'] %>
  username: <%= ENV['STACKHERO_MYSQL_USER'] %>
  password: <%= ENV['STACKHERO_MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV['STACKHERO_MYSQL_HOST'] %>
  port: <%= ENV['STACKHERO_MYSQL_PORT'] %>

cable:
  <<: *default
  database: <%= ENV['STACKHERO_MYSQL_DATABASE'] %>_cable
  username: <%= ENV['STACKHERO_MYSQL_USER'] %>
  password: <%= ENV['STACKHERO_MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV['STACKHERO_MYSQL_HOST'] %>
  port: <%= ENV['STACKHERO_MYSQL_PORT'] %>
