default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("MYSQL_DB") %>_development
  username: <%= ENV.fetch("MYSQL_USER") %>
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") %>
  host: db
  port: <%= ENV.fetch("MYSQL_PORT") { 3306 } %>

development:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DB") %>_development

test:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DB") %>_test


production:
  adapter: mysql2
  encoding: utf8mb4
  database: <%= ENV.fetch("STACKHERO_MYSQL_DATABASE", nil) %>
  username: <%= ENV.fetch("STACKHERO_MYSQL_USER", nil) %>
  password: <%= ENV.fetch("STACKHERO_MYSQL_ROOT_PASSWORD", nil) %>
  host: <%= ENV.fetch("STACKHERO_MYSQL_HOST", nil) %>
  port: <%= ENV.fetch("STACKHERO_MYSQL_PORT", nil) %>
  sslca: /etc/ssl/certs/ca-cert.pem

